export { ReactComponent as Add } from './add-icon.svg'
export { ReactComponent as Delete } from './delete-icon.svg'
export { ReactComponent as Editing } from './editing-icon.svg'
export { ReactComponent as Saving } from './saving-icon.svg'
export { ReactComponent as Saved } from './saved-icon.svg'
export { default as FileBlueIcon } from './file-blue-icon.svg'
export { FileIcon } from './file-icon'
